=== pauldpearson/XML/XML_Data_DU/HW3/president.dtd
<!--Paul Pearson-->
        <!--president.dtd-->

        <!DOCTYPE presidents [
        <!ELEMENT presidents (president)*>
        <!ELEMENT president (number|name|took_office|left_office|party|term)*>
        <!ELEMENT number (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT took_office (date) (#PCDATA)>
        <!ELEMENT left_office (date) (#PCDATA)>
        <!ELEMENT party (Republican, Democrat, Federalist) (#PCDATA)>
        <!ELEMENT term (number|vice_president)*>
        <!ELEMENT vice_president (#PCDATA)>
        ]>

=== pauldpearson/XML/XML_Data_DU/HW3a/USPresidents.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE presidents SYSTEM "president.dtd">

<!--Paul Pearson-->
<!--USPresidents.xml-->

<presidents>
    <president>
        <number>1</number>
        <name>George Washington</name>
        <took_office>April 30, 1789</took_office>
        <left_office>March 4, 1797</left_office>
        <party>no party</party>
        <term>
            <number>1</number>
            <vice_president>John Adams</vice_president>
        </term>
        <term>
            <number>2</number>
            <vice_president>John Adams</vice_president>
        </term>
    </president>

    <president>
        <number>2</number>
        <name>John Adams</name>
        <took_office>March 4, 1797</took_office>
        <left_office>March 4, 1801</left_office>
        <party>Federalist</party>
        <term>
            <number>3</number>
            <vice_president>Thomas Jefferson</vice_president>
        </term>
    </president>

    <president>
        <number>3</number>
        <name>Thomas Jefferson</name>
        <took_office>March 4, 1801</took_office>
        <left_office>March 4, 1809</left_office>
        <party>Democratic-Republican</party>
        <term>
            <number>4</number>
            <vice_president>Aaron Burr</vice_president>
        </term>
        <term>
            <number>5</number>
            <vice_president>George Clinton</vice_president>
        </term>
    </president>

    <president>
        <number>4</number>
        <name>James Madison</name>
        <took_office>March 4, 1809</took_office>
        <left_office>March 4, 1817</left_office>
        <party>Democratic-Republican</party>
        <term>
            <number>6</number>
            <vice_president>George Clinton</vice_president>
        </term>
        <term>
            <number>7</number>
            <vice_president>Elbridge Gerry</vice_president>
        </term>
    </president>

    <president>
        <number>5</number>
        <name>James Monroe</name>
        <took_office>March 4, 1817</took_office>
        <left_office>March 4, 1825</left_office>
        <party>Democratic-Republican</party>
        <term>
            <number>8</number>
            <vice_president>Daniel D. Tompkins</vice_president>
        </term>
        <term>
            <number>9</number>
            <vice_president>Daniel D. Tompkins</vice_president>
        </term>
    </president>

    <president>
        <number>6</number>
        <name>John Quincy Adams</name>
        <took_office>March 4, 1825</took_office>
        <left_office>March 4, 1829</left_office>
        <party>Democratic-Republican</party>
        <term>
            <number>10</number>
            <vice_president>John C. Calhoun</vice_president>
        </term>
    </president>

    <president>
        <number>7</number>
        <name>Andrew Jackson</name>
        <took_office>March 4, 1829</took_office>
        <left_office>March 4, 1837</left_office>
        <party>Democratic</party>
        <term>
            <number>11</number>
            <vice_president>John C. Calhoun</vice_president>
        </term>
        <term>
            <number>12</number>
            <vice_president>Martin Van Buren</vice_president>
        </term>
    </president>

    <president>
        <number>8</number>
        <name>Martin Van Buren</name>
        <took_office>March 4, 1837</took_office>
        <left_office>March 4, 1841</left_office>
        <party>Democratic</party>
        <term>
            <number>13</number>
            <vice_president>Richard Mentor Johnson</vice_president>
        </term>
    </president>

    <president>
        <number>9</number>
        <name>William Henry Harrison</name>
        <took_office>March 4, 1841</took_office>
        <left_office>April 4, 1841</left_office>
        <party></party>
        <term>
            <number>14</number>
            <vice_president>John Tyler</vice_president>
        </term>
    </president>

    <president>
        <number>10</number>
        <name>John Tyler</name>
        <took_office>April 4, 1841</took_office>
        <left_office>March 4, 1845</left_office>
        <party>Whig</party>
        <term>
            <number>14</number>
            <vice_president>None</vice_president>
        </term>
    </president>

    <president>
        <number>11</number>
        <name>James K. Polk</name>
        <took_office>March 4, 1845</took_office>
        <left_office>March 4, 1849</left_office>
        <party>Democratic</party>
        <term>
            <number>15</number>
            <vice_president>George M. Dallas</vice_president>
        </term>
    </president>

    <president>
        <number>12</number>
        <name>Zachary Taylor</name>
        <took_office>March 4, 1849</took_office>
        <left_office>July 9, 1850</left_office>
        <party>Whig</party>
        <term>
            <number>16</number>
            <vice_president>Millard Fillmore</vice_president>
        </term>
    </president>

    <president>
        <number>13</number>
        <name>Millard Fillmore</name>
        <took_office>July 9, 1850</took_office>
        <left_office>March 4, 1853</left_office>
        <party>Whig</party>
        <term>
            <number>16</number>
            <vice_president>None</vice_president>
        </term>
    </president>

    <president>
        <number>14</number>
        <name>Franklin Pierce</name>
        <took_office>March 4, 1853</took_office>
        <left_office>March 4, 1857</left_office>
        <party>Democratic</party>
        <term>
            <number>17</number>
            <vice_president>William R. King</vice_president>
        </term>
    </president>

    <president>
        <number>15</number>
        <name>James Buchanan</name>
        <took_office>March 4, 1857</took_office>
        <left_office>March 4, 1861</left_office>
        <party>Democratic</party>
        <term>
            <number>18</number>
            <vice_president>John C. Breckinridge</vice_president>
        </term>
    </president>

    <president>
        <number>16</number>
        <name>Abraham Lincoln</name>
        <took_office>March 4, 1861</took_office>
        <left_office>April 15, 1865</left_office>
        <party>Republican</party>
        <term>
            <number>19</number>
            <vice_president>Hannibal Hamlin</vice_president>
        </term>
        <term>
            <number>20</number>
            <vice_president>Andrew Johnson</vice_president>
        </term>
    </president>

    <president>
        <number>17</number>
        <name>Andrew Johnson</name>
        <took_office>April 15, 1865</took_office>
        <left_office>March 4, 1869</left_office>
        <party>Democratic</party>
        <term>
            <number>20</number>
            <vice_president>None</vice_president>
        </term>
    </president>

    <president>
        <number>18</number>
        <name>Ulysses S. Grant</name>
        <took_office>March 4, 1869</took_office>
        <left_office>March 4, 1877</left_office>
        <party>Republican</party>
        <term>
            <number>21</number>
            <vice_president>Schuyler Colfax</vice_president>
        </term>
        <term>
            <number>22</number>
            <vice_president>Henry Wilson</vice_president>
        </term>
    </president>

    <president>
        <number>19</number>
        <name>Rutherford B. Hayes</name>
        <took_office>March 4, 1877</took_office>
        <left_office>March 4, 1881</left_office>
        <party>Republican</party>
        <term>
            <number>23</number>
            <vice_president>William A. Wheeler</vice_president>
        </term>
    </president>

    <president>
        <number>20</number>
        <name>James A. Garfield</name>
        <took_office>March 4, 1881</took_office>
        <left_office>September 19, 1881</left_office>
        <party>Republican</party>
        <term>
            <number>24</number>
            <vice_president>Chester A. Arthur</vice_president>
        </term>
    </president>

    <president>
        <number>21</number>
        <name>Chester A. Arthur</name>
        <took_office>September 19, 1881</took_office>
        <left_office>March 4, 1885</left_office>
        <party>Republican</party>
        <term>
            <number>24</number>
            <vice_president>None</vice_president>
        </term>
    </president>

    <president>
        <number>22</number>
        <name>Grover Cleveland</name>
        <took_office>March 4, 1885</took_office>
        <left_office>March 4, 1889</left_office>
        <party>Democratic</party>
        <term>
            <number>25</number>
            <vice_president>Thomas A. Hendricks</vice_president>
        </term>
    </president>

    <president>
        <number>23</number>
        <name>Benjamin Harrison</name>
        <took_office>March 4, 1889</took_office>
        <left_office>March 4, 1893</left_office>
        <party>Republican</party>
        <term>
            <number>26</number>
            <vice_president>Levi P. Morton</vice_president>
        </term>
    </president>

    <president>
        <number>24</number>
        <name>Grover Cleveland</name>
        <took_office>March 4, 1893</took_office>
        <left_office>March 4, 1897</left_office>
        <party>Democratic</party>
        <term>
            <number>27</number>
            <vice_president>Adlai Stevenson I</vice_president>
        </term>
    </president>

    <president>
        <number>25</number>
        <name>William McKinley</name>
        <took_office>March 4, 1897</took_office>
        <left_office>September 14, 1901</left_office>
        <party>Republican</party>
        <term>
            <number>28</number>
            <vice_president>Garret Hobart</vice_president>
        </term>
        <term>
            <number>29</number>
            <vice_president>Theodore Roosevelt</vice_president>
        </term>
    </president>
